# Generated by Django 4.2.14 on 2024-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('daily_closing_price', models.FloatField()),
                ('percentage_change_1day', models.FloatField()),
                ('percentage_change_30days', models.FloatField()),
                ('percentage_change_365days', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopGainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('percentage_change_1day', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopLosers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('percentage_change_1day', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pricechange',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricechange',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='topgainer',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='toploser',
            name='stock',
        ),
        migrations.DeleteModel(
            name='DailyPrice',
        ),
        migrations.DeleteModel(
            name='PriceChange',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='TopGainer',
        ),
        migrations.DeleteModel(
            name='TopLoser',
        ),
    ]
