# Generated by Django 4.2.14 on 2024-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_symbolperformance_topgainers_toplosers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopGainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('percentage_change_1day', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopLoser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('percentage_change_1day', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='TopGainers',
        ),
        migrations.DeleteModel(
            name='TopLosers',
        ),
        migrations.AlterField(
            model_name='symbolperformance',
            name='symbol',
            field=models.TextField(),
        ),
    ]
